version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data/input:/app/data/input
    environment:
      - PYTHONPATH=/app
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VUE_APP_API_PROXY=http://backend:8000
      - VUE_APP_API_BASE_URL=/api
    depends_on:
      - backend
    command: npm run serve -- --host 0.0.0.0 --port 8080
